-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.benhnhan
(
    mabenhnhan serial NOT NULL,
    hoten character varying(100) COLLATE pg_catalog."default",
    gioitinh character varying(10) COLLATE pg_catalog."default",
    namsinh integer,
    socccd character varying(20) COLLATE pg_catalog."default",
    mabhyt character varying(20) COLLATE pg_catalog."default",
    quoctich character varying(50) COLLATE pg_catalog."default",
    dantoc character varying(50) COLLATE pg_catalog."default",
    diachi character varying(200) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    dienthoai character varying(20) COLLATE pg_catalog."default",
    nghenghiep character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT benhnhan_pkey PRIMARY KEY (mabenhnhan)
);

CREATE TABLE IF NOT EXISTS public.canlamsang
(
    madichvu integer NOT NULL DEFAULT nextval('dichvu_madichvu_seq'::regclass),
    tendichvu character varying(200) COLLATE pg_catalog."default",
    loaidichvu character varying(100) COLLATE pg_catalog."default",
    gia numeric(18, 2),
    mota character varying(300) COLLATE pg_catalog."default",
    trangthai character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dichvu_pkey PRIMARY KEY (madichvu)
);

CREATE TABLE IF NOT EXISTS public.chidinhcanlamsang
(
    machidinh serial NOT NULL,
    mahosokham integer,
    madichvu integer,
    bacsichidinh integer,
    ngaychidinh date,
    giochidinh character varying(20) COLLATE pg_catalog."default",
    trangthai character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT chidinhcanlamsang_pkey PRIMARY KEY (machidinh)
);

CREATE TABLE IF NOT EXISTS public.chitietdonthuoc
(
    id serial NOT NULL,
    madonthuoc integer,
    mathuoc integer,
    soluong integer,
    lieudung character varying(200) COLLATE pg_catalog."default",
    cachdung character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT chitietdonthuoc_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chuyenkhoa
(
    machuyenkhoa serial NOT NULL,
    tenchuyenkhoa character varying(150) COLLATE pg_catalog."default" NOT NULL,
    mota text COLLATE pg_catalog."default",
    trangthai boolean DEFAULT true,
    CONSTRAINT chuyenkhoa_pkey PRIMARY KEY (machuyenkhoa)
);

CREATE TABLE IF NOT EXISTS public.dangkyhenkham
(
    id serial NOT NULL,
    hoten character varying(100) COLLATE pg_catalog."default",
    socccd character varying(20) COLLATE pg_catalog."default",
    sodienthoai character varying(20) COLLATE pg_catalog."default",
    namsinh integer,
    loaikham character varying(100) COLLATE pg_catalog."default",
    lydokham character varying(200) COLLATE pg_catalog."default",
    ngaykham date,
    giokham character varying(20) COLLATE pg_catalog."default",
    ngaydangky date,
    trangthai character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dangkyhenkham_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.danhmucthuoc
(
    mathuoc serial NOT NULL,
    tenthuoc character varying(200) COLLATE pg_catalog."default",
    hamluong character varying(100) COLLATE pg_catalog."default",
    nhomthuoc character varying(100) COLLATE pg_catalog."default",
    donvi character varying(50) COLLATE pg_catalog."default",
    giaban numeric(18, 2),
    nhacungcap character varying(200) COLLATE pg_catalog."default",
    chophepbanweb boolean,
    CONSTRAINT danhmucthuoc_pkey PRIMARY KEY (mathuoc)
);

CREATE TABLE IF NOT EXISTS public.danhmucvattu
(
    mavattu serial NOT NULL,
    tenvattu character varying(200) COLLATE pg_catalog."default",
    loaivattu character varying(100) COLLATE pg_catalog."default",
    nhasanxuat character varying(200) COLLATE pg_catalog."default",
    hangsanxuat character varying(200) COLLATE pg_catalog."default",
    thanhphan character varying(300) COLLATE pg_catalog."default",
    huongdansudung character varying(300) COLLATE pg_catalog."default",
    congdung character varying(200) COLLATE pg_catalog."default",
    doituongsudung character varying(100) COLLATE pg_catalog."default",
    chophepbanweb boolean,
    giaban numeric(18, 2) DEFAULT 0,
    CONSTRAINT danhmucvattu_pkey PRIMARY KEY (mavattu)
);

CREATE TABLE IF NOT EXISTS public.donthuoc
(
    madonthuoc serial NOT NULL,
    bacsikedon integer,
    ngaykedon date,
    mabenhnhan integer,
    CONSTRAINT donthuoc_pkey PRIMARY KEY (madonthuoc),
    CONSTRAINT uq_donthuoc_madonthuoc UNIQUE (madonthuoc)
);

CREATE TABLE IF NOT EXISTS public.hoadon_dichvu
(
    id serial NOT NULL,
    mahoadon integer,
    madichvu integer,
    soluong integer,
    dongia numeric(18, 2),
    thanhtien numeric(18, 2),
    CONSTRAINT hoadon_dichvu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hoadonthanhtoan
(
    mahoadon serial NOT NULL,
    mabenhnhan integer,
    danhsachdichvu text COLLATE pg_catalog."default",
    sotienbaohiemchitra numeric(18, 2),
    thuctracuabenhnhan numeric(18, 2),
    tongtien numeric(18, 2),
    CONSTRAINT hoadonthanhtoan_pkey PRIMARY KEY (mahoadon)
);

CREATE TABLE IF NOT EXISTS public.hosokhambenh
(
    mahosokham serial NOT NULL,
    mabenhnhan integer,
    khoakham character varying(100) COLLATE pg_catalog."default",
    bacsiphutrach integer,
    lydokham character varying(300) COLLATE pg_catalog."default",
    trieuchungbandau character varying(300) COLLATE pg_catalog."default",
    tieusubenh character varying(300) COLLATE pg_catalog."default",
    tiensuphauthuat character varying(300) COLLATE pg_catalog."default",
    diung character varying(200) COLLATE pg_catalog."default",
    chandoansobo character varying(300) COLLATE pg_catalog."default",
    ketluan character varying(300) COLLATE pg_catalog."default",
    ngayhentaikham date,
    ketquacanlamsang character varying(200) COLLATE pg_catalog."default",
    trangthai character varying(50) COLLATE pg_catalog."default",
    maluotkham integer,
    madonthuoc integer,
    CONSTRAINT hosokhambenh_pkey PRIMARY KEY (mahosokham),
    CONSTRAINT uq_hosokhambenh_madonthuoc UNIQUE (madonthuoc)
);

CREATE TABLE IF NOT EXISTS public.ketquacanlamsang
(
    maketqua serial NOT NULL,
    machidinh integer,
    fileketqua character varying(300) COLLATE pg_catalog."default",
    ketluan character varying(300) COLLATE pg_catalog."default",
    bacsithuchien integer,
    thoigiantraketqua timestamp without time zone,
    CONSTRAINT ketquacanlamsang_pkey PRIMARY KEY (maketqua)
);

CREATE TABLE IF NOT EXISTS public.lichlamviec
(
    id serial NOT NULL,
    manhanvien integer,
    maphong integer,
    calam character varying(50) COLLATE pg_catalog."default",
    ngay date,
    ghichu character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT lichlamviec_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lichsubenhan
(
    id serial NOT NULL,
    mabenhnhan integer,
    diung character varying(200) COLLATE pg_catalog."default",
    tiensubenh character varying(300) COLLATE pg_catalog."default",
    tiensuphauthuat character varying(300) COLLATE pg_catalog."default",
    benhnen character varying(200) COLLATE pg_catalog."default",
    ghichu character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT lichsubenhan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.luotkham
(
    maluotkham serial NOT NULL,
    mabenhnhan integer NOT NULL,
    ngaykham date NOT NULL,
    lydokham character varying(255) COLLATE pg_catalog."default",
    loaihinhkham character varying(100) COLLATE pg_catalog."default",
    trangthai character varying(50) COLLATE pg_catalog."default",
    maphong integer,
    CONSTRAINT luotkham_pkey PRIMARY KEY (maluotkham)
);

CREATE TABLE IF NOT EXISTS public.nhanvien
(
    manhanvien serial NOT NULL,
    anh character varying(200) COLLATE pg_catalog."default",
    hoten character varying(100) COLLATE pg_catalog."default",
    ngaysinh date,
    gioitinh character varying(10) COLLATE pg_catalog."default",
    socccd character varying(20) COLLATE pg_catalog."default",
    sdt character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    chucvu character varying(100) COLLATE pg_catalog."default",
    hocham character varying(100) COLLATE pg_catalog."default",
    chuyenkhoa character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT nhanvien_pkey PRIMARY KEY (manhanvien)
);

CREATE TABLE IF NOT EXISTS public.phieunhap
(
    maphieunhap serial NOT NULL,
    mavattu integer,
    gia numeric(18, 2),
    soluong integer,
    donvitinh character varying(50) COLLATE pg_catalog."default",
    phongluutru character varying(50) COLLATE pg_catalog."default",
    keluutru character varying(50) COLLATE pg_catalog."default",
    hansudung date,
    nhacungcap character varying(200) COLLATE pg_catalog."default",
    trangthaivattu character varying(50) COLLATE pg_catalog."default",
    ghichu character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT phieunhap_pkey PRIMARY KEY (maphieunhap)
);

CREATE TABLE IF NOT EXISTS public.phongkham
(
    maphong serial NOT NULL,
    tenphong character varying(100) COLLATE pg_catalog."default",
    chucnang character varying(200) COLLATE pg_catalog."default",
    tang character varying(10) COLLATE pg_catalog."default",
    khu character varying(50) COLLATE pg_catalog."default",
    trangthai character varying(50) COLLATE pg_catalog."default",
    mamayphong character varying(100) COLLATE pg_catalog."default",
    machuyenkhoa integer,
    CONSTRAINT phongkham_pkey PRIMARY KEY (maphong)
);

CREATE TABLE IF NOT EXISTS public.taikhoan
(
    mataikhoan serial NOT NULL,
    tentaikhoan character varying(50) COLLATE pg_catalog."default",
    matkhau character varying(200) COLLATE pg_catalog."default",
    manguoidung integer,
    trangthai character varying(50) COLLATE pg_catalog."default",
    loaitaikhoan character varying(50) COLLATE pg_catalog."default",
    isdelete boolean,
    CONSTRAINT taikhoan_pkey PRIMARY KEY (mataikhoan)
);

ALTER TABLE IF EXISTS public.chidinhcanlamsang
    ADD CONSTRAINT chidinhcanlamsang_madichvu_fkey FOREIGN KEY (madichvu)
    REFERENCES public.canlamsang (madichvu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chidinhcanlamsang
    ADD CONSTRAINT chidinhcanlamsang_mahosokham_fkey FOREIGN KEY (mahosokham)
    REFERENCES public.hosokhambenh (mahosokham) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chitietdonthuoc
    ADD CONSTRAINT chitietdonthuoc_madonthuoc_fkey FOREIGN KEY (madonthuoc)
    REFERENCES public.donthuoc (madonthuoc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hoadon_dichvu
    ADD CONSTRAINT hoadon_dichvu_madichvu_fkey FOREIGN KEY (madichvu)
    REFERENCES public.canlamsang (madichvu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hoadonthanhtoan
    ADD CONSTRAINT hoadonthanhtoan_mabenhnhan_fkey FOREIGN KEY (mabenhnhan)
    REFERENCES public.benhnhan (mabenhnhan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hosokhambenh
    ADD CONSTRAINT fk_hoso_luotkham FOREIGN KEY (maluotkham)
    REFERENCES public.luotkham (maluotkham) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.hosokhambenh
    ADD CONSTRAINT fk_hosokhambenh_donthuoc FOREIGN KEY (madonthuoc)
    REFERENCES public.donthuoc (madonthuoc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uq_hosokhambenh_madonthuoc
    ON public.hosokhambenh(madonthuoc);


ALTER TABLE IF EXISTS public.hosokhambenh
    ADD CONSTRAINT hosokhambenh_mabenhnhan_fkey FOREIGN KEY (mabenhnhan)
    REFERENCES public.benhnhan (mabenhnhan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ketquacanlamsang
    ADD CONSTRAINT ketquacanlamsang_machidinh_fkey FOREIGN KEY (machidinh)
    REFERENCES public.chidinhcanlamsang (machidinh) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lichlamviec
    ADD CONSTRAINT lichlamviec_manhanvien_fkey FOREIGN KEY (manhanvien)
    REFERENCES public.nhanvien (manhanvien) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lichlamviec
    ADD CONSTRAINT lichlamviec_maphong_fkey FOREIGN KEY (maphong)
    REFERENCES public.phongkham (maphong) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lichsubenhan
    ADD CONSTRAINT lichsubenhan_mabenhnhan_fkey FOREIGN KEY (mabenhnhan)
    REFERENCES public.benhnhan (mabenhnhan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.luotkham
    ADD CONSTRAINT fk_luotkham_benhnhan FOREIGN KEY (mabenhnhan)
    REFERENCES public.benhnhan (mabenhnhan) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.luotkham
    ADD CONSTRAINT fk_luotkham_phongkham FOREIGN KEY (maphong)
    REFERENCES public.phongkham (maphong) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.phieunhap
    ADD CONSTRAINT phieunhap_mavattu_fkey FOREIGN KEY (mavattu)
    REFERENCES public.danhmucvattu (mavattu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.phongkham
    ADD CONSTRAINT fk_phongkham_chuyenkhoa FOREIGN KEY (machuyenkhoa)
    REFERENCES public.chuyenkhoa (machuyenkhoa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.taikhoan
    ADD CONSTRAINT taikhoan_manguoidung_fkey FOREIGN KEY (manguoidung)
    REFERENCES public.nhanvien (manhanvien) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;